name: Build WebView APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Android build tools
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip zipalign apksigner

    - name: Prepare build directory
      run: |
        mkdir -p build
        cp -r res build/
        cp -r assets build/
        cp AndroidManifest.xml build/

    - name: Compile resources
      run: |
        aapt2 compile -o build/res.zip build/res/**/*.xml
        aapt2 link -o build/output.apk \
          -I $ANDROID_HOME/platforms/android-33/android.jar \
          --manifest build/AndroidManifest.xml \
          -R build/res.zip \
          --assets build/assets \
          --output-to-dir

    - name: Sign APK
      run: |
        keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 \
          -alias my-key-alias -storepass 123456 -keypass 123456 -dname "CN=QuranViewer, OU=Dev, O=Mohamad, L=Amman, S=Jordan, C=JO"
        apksigner sign --ks my-release-key.jks --ks-key-alias my-key-alias \
          --ks-pass pass:123456 --key-pass pass:123456 \
          --out build/QuranViewer.apk build/output.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: QuranViewer
        path: build/QuranViewer.apk
