name: Build WebView APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Android SDK
      uses: actions/setup-android@v3
      with:
        sdk: 'default'
        build-tools: '33.0.2'
        ndk: 'default'

    - name: Prepare build directory
      run: |
        mkdir -p build
        [ -d res ] && cp -r res build/ || echo "res directory not found"
        [ -d assets ] && cp -r assets build/ || echo "assets directory not found"
        [ -f AndroidManifest.xml ] && cp AndroidManifest.xml build/ || echo "AndroidManifest.xml not found"

    - name: Compile resources
      run: |
        $ANDROID_HOME/build-tools/33.0.2/aapt2 compile -o build/res.zip build/res/*
        $ANDROID_HOME/build-tools/33.0.2/aapt2 link -o build/output.apk \
          -I $ANDROID_HOME/platforms/android-33/android.jar \
          --manifest build/AndroidManifest.xml \
          -R build/res.zip \
          --assets build/assets \
          --output-to-dir

    - name: Generate keystore and sign APK
      run: |
        keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -storepass 123456 -keypass 123456 -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
        $ANDROID_HOME/build-tools/33.0.2/zipalign -v 4 build/output.apk build/aligned.apk
        $ANDROID_HOME/build-tools/33.0.2/apksigner sign --ks my-release-key.jks --ks-key-alias my-key-alias --ks-pass pass:123456 --key-pass pass:123456 --out build/QuranViewer.apk build/aligned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: QuranViewer
        path: build/QuranViewer.apk
